### ISSUE TITLE
Prevent Furigana from being selected

### ISSUE THREAD

**Issue by herobs** [donkuri/Kaishi#58]
Add the following CSS can prevent Furigana being selected. It's really a huge headache for me when I want copy the sentence.

```css
ruby > rt {
	user-select: none;
}
```

Tested with the newest Anki.
